# -*- coding: utf-8 -*-
"""cattle_buffalo_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9_83r29VS1zHAKdYnbpX_mM0WYPPGgP

# Image Based Animal Type Classification for Cattle and Buffaloes

This notebook implements a deep learning model using transfer learning to classify images of cattle and buffaloes.

## Dataset
Dataset: [Cows and Buffalo Computer Vision Dataset](https://www.kaggle.com/datasets/raghavdharwal/cows-and-buffalo-computer-vision-dataset)

## 1. Import Required Libraries
"""

# Install required packages (uncomment if needed)
!pip install tensorflow keras numpy matplotlib scikit-learn pillow kaggle opendatasets pyyaml

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import shutil
import warnings
import yaml
from collections import Counter
warnings.filterwarnings('ignore')

# TensorFlow and Keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.applications import MobileNetV2, ResNet50, EfficientNetB0
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# Metrics
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU Available: {tf.config.list_physical_devices('GPU')}")

"""## 2. Download and Setup Dataset"""

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Download dataset using opendatasets (alternative to kaggle API)
# You'll need to authenticate with Kaggle credentials

import opendatasets as od

dataset_url = 'https://www.kaggle.com/datasets/raghavdharwal/cows-and-buffalo-computer-vision-dataset'

# This will prompt for Kaggle username and API key
# You can get your API key from: https://www.kaggle.com/settings/account
od.download(dataset_url)

# Set dataset path
dataset_dir = 'cows-and-buffalo-computer-vision-dataset'
print(f"Dataset downloaded to: {dataset_dir}")

# Explore dataset structure
for root, dirs, files in os.walk(dataset_dir):
    level = root.replace(dataset_dir, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 2 * (level + 1)
    for file in files[:3]:  # Show first 3 files only
        print(f'{subindent}{file}')
    if len(files) > 3:
        print(f'{subindent}... and {len(files) - 3} more files')

"""## 3. Parse YOLO Format and Reorganize Dataset"""

# Read the data.yaml file to get class names
yaml_path = os.path.join(dataset_dir, 'data.yaml')

with open(yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)

print("Dataset configuration:")
print(data_config)

# Get class names
class_names = data_config['names']
num_classes = data_config['nc']

print(f"\nNumber of classes: {num_classes}")
print(f"Class names: {class_names}")

# Function to parse YOLO label files and reorganize dataset
def reorganize_yolo_to_classification(dataset_dir, output_dir='organized_dataset'):
    """
    Convert YOLO format dataset to classification format.
    YOLO format has images and labels in separate folders.
    This function creates a folder structure: output_dir/class_name/image.jpg
    """

    # Paths
    train_images_dir = os.path.join(dataset_dir, 'train', 'images')
    train_labels_dir = os.path.join(dataset_dir, 'train', 'labels')

    # Check if validation/test exists
    valid_images_dir = os.path.join(dataset_dir, 'valid', 'images')
    valid_labels_dir = os.path.join(dataset_dir, 'valid', 'labels')
    test_images_dir = os.path.join(dataset_dir, 'test', 'images')
    test_labels_dir = os.path.join(dataset_dir, 'test', 'labels')

    has_valid = os.path.exists(valid_images_dir)
    has_test = os.path.exists(test_images_dir)

    print(f"Has validation set: {has_valid}")
    print(f"Has test set: {has_test}")

    # Create output directories
    train_output = os.path.join(output_dir, 'train')
    test_output = os.path.join(output_dir, 'test')

    for class_name in class_names:
        os.makedirs(os.path.join(train_output, class_name), exist_ok=True)
        os.makedirs(os.path.join(test_output, class_name), exist_ok=True)

    # Process training images
    print("\nProcessing training images...")
    train_stats = process_split(train_images_dir, train_labels_dir, train_output, class_names)

    # If no separate test/valid set, split from training
    if not has_valid and not has_test:
        print("\nNo validation/test set found. Creating test split from training data...")
        split_train_test(train_output, test_output, test_size=0.2)
    elif has_valid:
        print("\nProcessing validation images as test set...")
        test_stats = process_split(valid_images_dir, valid_labels_dir, test_output, class_names)
    elif has_test:
        print("\nProcessing test images...")
        test_stats = process_split(test_images_dir, test_labels_dir, test_output, class_names)

    print("\n✅ Dataset reorganization complete!")
    return train_output, test_output

def process_split(images_dir, labels_dir, output_dir, class_names):
    """
    Process a single split (train/valid/test)
    """
    stats = Counter()

    # Get all image files
    image_files = [f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    for img_file in image_files:
        # Get corresponding label file
        label_file = os.path.splitext(img_file)[0] + '.txt'
        label_path = os.path.join(labels_dir, label_file)
        img_path = os.path.join(images_dir, img_file)

        # Read label file to get class
        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                lines = f.readlines()
                if lines:
                    # YOLO format: class_id x_center y_center width height
                    # We only need the class_id (first value)
                    class_id = int(lines[0].split()[0])
                    class_name = class_names[class_id]

                    # Copy image to appropriate class folder
                    dest_path = os.path.join(output_dir, class_name, img_file)
                    shutil.copy2(img_path, dest_path)

                    stats[class_name] += 1

    print(f"  Processed {sum(stats.values())} images")
    for class_name, count in stats.items():
        print(f"    {class_name}: {count} images")

    return stats

def split_train_test(train_dir, test_dir, test_size=0.2):
    """
    Split training data into train and test sets
    """
    for class_name in os.listdir(train_dir):
        class_train_dir = os.path.join(train_dir, class_name)
        class_test_dir = os.path.join(test_dir, class_name)

        if os.path.isdir(class_train_dir):
            # Get all images
            images = [f for f in os.listdir(class_train_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

            if images: # Add check for non-empty list of images
                # Split
                train_imgs, test_imgs = train_test_split(images, test_size=test_size, random_state=42)

                # Move test images
                for img in test_imgs:
                    src = os.path.join(class_train_dir, img)
                    dst = os.path.join(class_test_dir, img)
                    shutil.move(src, dst)

                print(f"  {class_name}: {len(train_imgs)} train, {len(test_imgs)} test")
            else:
                print(f"  {class_name}: No images found for splitting, skipping.")

# Reorganize the dataset
train_dir, test_dir = reorganize_yolo_to_classification(dataset_dir)

"""## 4. Data Configuration and Exploration"""

# Image parameters
IMG_HEIGHT = 224
IMG_WIDTH = 224
BATCH_SIZE = 32
EPOCHS = 30
LEARNING_RATE = 0.001

print(f"Train directory: {train_dir}")
print(f"Test directory: {test_dir}")

# Count images in each category
def count_images(directory):
    class_counts = {}
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if os.path.isdir(class_path):
            num_images = len([f for f in os.listdir(class_path)
                            if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
            class_counts[class_name] = num_images
    return class_counts

train_counts = count_images(train_dir)
test_counts = count_images(test_dir)

print("\n" + "="*50)
print("DATASET STATISTICS")
print("="*50)

print("\nTraining set:")
for class_name, count in train_counts.items():
    print(f"  {class_name}: {count} images")
print(f"  Total: {sum(train_counts.values())} images")

print("\nTest set:")
for class_name, count in test_counts.items():
    print(f"  {class_name}: {count} images")
print(f"  Total: {sum(test_counts.values())} images")

print(f"\nTotal dataset: {sum(train_counts.values()) + sum(test_counts.values())} images")

# Visualize class distribution
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Training set
axes[0].bar(train_counts.keys(), train_counts.values(), color='skyblue', edgecolor='navy', linewidth=1.5)
axes[0].set_title('Training Set Distribution', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Class', fontsize=12)
axes[0].set_ylabel('Number of Images', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(axis='y', alpha=0.3)

# Add value labels on bars
for i, (k, v) in enumerate(train_counts.items()):
    axes[0].text(i, v, str(v), ha='center', va='bottom', fontweight='bold')

# Test set
axes[1].bar(test_counts.keys(), test_counts.values(), color='lightcoral', edgecolor='darkred', linewidth=1.5)
axes[1].set_title('Test Set Distribution', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Class', fontsize=12)
axes[1].set_ylabel('Number of Images', fontsize=12)
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(axis='y', alpha=0.3)

# Add value labels on bars
for i, (k, v) in enumerate(test_counts.items()):
    axes[1].text(i, v, str(v), ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('class_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# Display sample images from each class
def display_sample_images(directory, num_samples=5):
    classes = sorted([d for d in os.listdir(directory) if os.path.isdir(os.path.join(directory, d))])

    fig, axes = plt.subplots(len(classes), num_samples, figsize=(15, 3.5 * len(classes)))

    if len(classes) == 1:
        axes = axes.reshape(1, -1)

    for i, class_name in enumerate(classes):
        class_path = os.path.join(directory, class_name)
        images = [f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

        # Randomly sample images
        sample_images = np.random.choice(images, min(num_samples, len(images)), replace=False)

        for j, img_name in enumerate(sample_images):
            img_path = os.path.join(class_path, img_name)
            img = load_img(img_path, target_size=(IMG_HEIGHT, IMG_WIDTH))

            axes[i, j].imshow(img)
            axes[i, j].axis('off')

            if j == 0:
                axes[i, j].set_title(f'{class_name}', fontsize=14, fontweight='bold', loc='left')

        # Hide unused subplots
        for j in range(len(sample_images), num_samples):
            axes[i, j].axis('off')

    plt.suptitle('Sample Images from Training Set', fontsize=16, fontweight='bold', y=1.00)
    plt.tight_layout()
    plt.savefig('sample_images.png', dpi=300, bbox_inches='tight')
    plt.show()

display_sample_images(train_dir, num_samples=5)

"""## 5. Data Augmentation and Generators"""

# Data augmentation for training
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

# No augmentation for test data
test_datagen = ImageDataGenerator(rescale=1./255)

# Create data generators
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

validation_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

# Get class names and number of classes
class_names_from_gen = list(train_generator.class_indices.keys())
num_classes = len(class_names_from_gen)

print(f"\n{'='*50}")
print("DATA GENERATORS CREATED")
print(f"{'='*50}")
print(f"Number of classes: {num_classes}")
print(f"Class names: {class_names_from_gen}")
print(f"Class indices: {train_generator.class_indices}")
print(f"\nTraining samples: {train_generator.samples}")
print(f"Validation samples: {validation_generator.samples}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Steps per epoch (train): {train_generator.samples // BATCH_SIZE}")
print(f"Validation steps: {validation_generator.samples // BATCH_SIZE}")

"""## 6. Build Transfer Learning Model"""

def create_transfer_learning_model(base_model_name='MobileNetV2', num_classes=2):
    """
    Create a transfer learning model using pre-trained base models.

    Args:
        base_model_name: Name of the pre-trained model ('MobileNetV2', 'ResNet50', 'EfficientNetB0')
        num_classes: Number of output classes

    Returns:
        Compiled Keras model
    """

    print(f"\nCreating transfer learning model with {base_model_name}...")

    # Load pre-trained base model
    if base_model_name == 'MobileNetV2':
        base_model = MobileNetV2(
            input_shape=(IMG_HEIGHT, IMG_WIDTH, 3),
            include_top=False,
            weights='imagenet'
        )
    elif base_model_name == 'ResNet50':
        base_model = ResNet50(
            input_shape=(IMG_HEIGHT, IMG_WIDTH, 3),
            include_top=False,
            weights='imagenet'
        )
    elif base_model_name == 'EfficientNetB0':
        base_model = EfficientNetB0(
            input_shape=(IMG_HEIGHT, IMG_WIDTH, 3),
            include_top=False,
            weights='imagenet'
        )
    else:
        raise ValueError(f"Unknown base model: {base_model_name}")

    # Freeze base model layers
    base_model.trainable = False

    # Create new model on top
    model = Sequential([
        base_model,
        GlobalAveragePooling2D(),
        BatchNormalization(),
        Dense(256, activation='relu'),
        Dropout(0.5),
        BatchNormalization(),
        Dense(128, activation='relu'),
        Dropout(0.3),
        Dense(num_classes, activation='softmax')
    ])

    # Compile model
    model.compile(
        optimizer=Adam(learning_rate=LEARNING_RATE),
        loss='categorical_crossentropy',
        metrics=['accuracy', tf.keras.metrics.AUC(name='auc'),
                tf.keras.metrics.Precision(name='precision'),
                tf.keras.metrics.Recall(name='recall')]
    )

    return model, base_model

# Create model
model, base_model = create_transfer_learning_model('MobileNetV2', num_classes)

print("\n" + "="*50)
print("MODEL ARCHITECTURE")
print("="*50)
model.summary()

"""## 7. Setup Callbacks"""

# Create callbacks
callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=7,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=3,
        min_lr=1e-7,
        verbose=1
    ),
    ModelCheckpoint(
        'best_model.h5',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]

print("Callbacks configured:")
print("  ✓ Early Stopping (patience=7)")
print("  ✓ Learning Rate Reduction (factor=0.5, patience=3)")
print("  ✓ Model Checkpoint (save best model)")

"""## 8. Train the Model - Phase 1: Transfer Learning"""

# Train the model
print("\n" + "="*70)
print("STARTING TRAINING - PHASE 1: TRANSFER LEARNING")
print("="*70)
print(f"Base model layers frozen: {not base_model.trainable}")
print(f"Training epochs: {EPOCHS}")
print(f"Learning rate: {LEARNING_RATE}")
print("="*70 + "\n")

history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1
)

print("\n" + "="*70)
print("✅ PHASE 1 TRAINING COMPLETED!")
print("="*70)

"""## 9. Fine-tuning - Phase 2"""

# Fine-tune the model by unfreezing some layers
print("\n" + "="*70)
print("STARTING TRAINING - PHASE 2: FINE-TUNING")
print("="*70)

# Unfreeze the base model
base_model.trainable = True

# Freeze all layers except the last 30
for layer in base_model.layers[:-30]:
    layer.trainable = False

print(f"Total layers in base model: {len(base_model.layers)}")
print(f"Trainable layers: {sum([layer.trainable for layer in base_model.layers])}")

# Recompile with a lower learning rate
fine_tune_lr = LEARNING_RATE / 10
model.compile(
    optimizer=Adam(learning_rate=fine_tune_lr),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc'),
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall')]
)

print(f"Fine-tuning learning rate: {fine_tune_lr}")
print("="*70 + "\n")

# Continue training
fine_tune_epochs = 15
history_fine = model.fit(
    train_generator,
    epochs=fine_tune_epochs,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1
)

print("\n" + "="*70)
print("✅ PHASE 2 FINE-TUNING COMPLETED!")
print("="*70)

"""## 10. Visualize Training History"""

# Plot training history
def plot_training_history(history, history_fine=None):
    # Combine histories if fine-tuning was done
    if history_fine:
        acc = history.history['accuracy'] + history_fine.history['accuracy']
        val_acc = history.history['val_accuracy'] + history_fine.history['val_accuracy']
        loss = history.history['loss'] + history_fine.history['loss']
        val_loss = history.history['val_loss'] + history_fine.history['val_loss']
        auc_score = history.history['auc'] + history_fine.history['auc']
        val_auc = history.history['val_auc'] + history_fine.history['val_auc']

        phase1_epochs = len(history.history['accuracy'])
    else:
        acc = history.history['accuracy']
        val_acc = history.history['val_accuracy']
        loss = history.history['loss']
        val_loss = history.history['val_loss']
        auc_score = history.history['auc']
        val_auc = history.history['val_auc']
        phase1_epochs = None

    epochs_range = range(1, len(acc) + 1)

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))

    # Accuracy
    axes[0, 0].plot(epochs_range, acc, 'b-', label='Training Accuracy', linewidth=2.5)
    axes[0, 0].plot(epochs_range, val_acc, 'r-', label='Validation Accuracy', linewidth=2.5)
    if phase1_epochs:
        axes[0, 0].axvline(x=phase1_epochs, color='green', linestyle='--', linewidth=2, label='Fine-tuning starts')
    axes[0, 0].set_xlabel('Epoch', fontsize=12, fontweight='bold')
    axes[0, 0].set_ylabel('Accuracy', fontsize=12, fontweight='bold')
    axes[0, 0].set_title('Model Accuracy', fontsize=14, fontweight='bold')
    axes[0, 0].legend(fontsize=10)
    axes[0, 0].grid(True, alpha=0.3)

    # Loss
    axes[0, 1].plot(epochs_range, loss, 'b-', label='Training Loss', linewidth=2.5)
    axes[0, 1].plot(epochs_range, val_loss, 'r-', label='Validation Loss', linewidth=2.5)
    if phase1_epochs:
        axes[0, 1].axvline(x=phase1_epochs, color='green', linestyle='--', linewidth=2, label='Fine-tuning starts')
    axes[0, 1].set_xlabel('Epoch', fontsize=12, fontweight='bold')
    axes[0, 1].set_ylabel('Loss', fontsize=12, fontweight='bold')
    axes[0, 1].set_title('Model Loss', fontsize=14, fontweight='bold')
    axes[0, 1].legend(fontsize=10)
    axes[0, 1].grid(True, alpha=0.3)

    # AUC
    axes[1, 0].plot(epochs_range, auc_score, 'b-', label='Training AUC', linewidth=2.5)
    axes[1, 0].plot(epochs_range, val_auc, 'r-', label='Validation AUC', linewidth=2.5)
    if phase1_epochs:
        axes[1, 0].axvline(x=phase1_epochs, color='green', linestyle='--', linewidth=2, label='Fine-tuning starts')
    axes[1, 0].set_xlabel('Epoch', fontsize=12, fontweight='bold')
    axes[1, 0].set_ylabel('AUC', fontsize=12, fontweight='bold')
    axes[1, 0].set_title('Model AUC Score', fontsize=14, fontweight='bold')
    axes[1, 0].legend(fontsize=10)
    axes[1, 0].grid(True, alpha=0.3)

    # Accuracy vs Loss comparison
    ax2 = axes[1, 1]
    ax2.plot(epochs_range, val_acc, 'g-', label='Val Accuracy', linewidth=2.5)
    ax2.set_xlabel('Epoch', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Validation Accuracy', fontsize=12, fontweight='bold', color='g')
    ax2.tick_params(axis='y', labelcolor='g')

    ax2_twin = ax2.twinx()
    ax2_twin.plot(epochs_range, val_loss, 'r-', label='Val Loss', linewidth=2.5)
    ax2_twin.set_ylabel('Validation Loss', fontsize=12, fontweight='bold', color='r')
    ax2_twin.tick_params(axis='y', labelcolor='r')

    if phase1_epochs:
        ax2.axvline(x=phase1_epochs, color='blue', linestyle='--', linewidth=2)

    ax2.set_title('Validation Accuracy vs Loss', fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('training_history.png', dpi=300, bbox_inches='tight')
    plt.show()

plot_training_history(history, history_fine if 'history_fine' in locals() else None)

"""## 11. Evaluate Model on Test Data"""

# Evaluate on test set
print("\n" + "="*70)
print("EVALUATING MODEL ON TEST DATA")
print("="*70 + "\n")

results = model.evaluate(validation_generator, verbose=1)

print(f"\n" + "="*70)
print("TEST RESULTS")
print("="*70)
print(f"  Loss:      {results[0]:.4f}")
print(f"  Accuracy:  {results[1]:.4f} ({results[1]*100:.2f}%)")
print(f"  AUC:       {results[2]:.4f}")
print(f"  Precision: {results[3]:.4f}")
print(f"  Recall:    {results[4]:.4f}")
print("="*70)

test_loss = results[0]
test_accuracy = results[1]
test_auc = results[2]
test_precision = results[3]
test_recall = results[4]

"""## 12. Generate Predictions and Confusion Matrix"""

# Generate predictions
print("Generating predictions on test set...")
validation_generator.reset()
predictions = model.predict(validation_generator, verbose=1)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = validation_generator.classes

print(f"Predictions shape: {predictions.shape}")
print(f"Number of predictions: {len(predicted_classes)}")

# Confusion Matrix
cm = confusion_matrix(true_classes, predicted_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names_from_gen, yticklabels=class_names_from_gen,
            cbar_kws={'label': 'Count'}, linewidths=1, linecolor='gray')
plt.xlabel('Predicted Label', fontsize=13, fontweight='bold')
plt.ylabel('True Label', fontsize=13, fontweight='bold')
plt.title('Confusion Matrix', fontsize=15, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# Normalized Confusion Matrix
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(10, 8))
sns.heatmap(cm_normalized, annot=True, fmt='.2%', cmap='Greens',
            xticklabels=class_names_from_gen, yticklabels=class_names_from_gen,
            cbar_kws={'label': 'Percentage'}, linewidths=1, linecolor='gray',
            vmin=0, vmax=1)
plt.xlabel('Predicted Label', fontsize=13, fontweight='bold')
plt.ylabel('True Label', fontsize=13, fontweight='bold')
plt.title('Normalized Confusion Matrix (Percentages)', fontsize=15, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('confusion_matrix_normalized.png', dpi=300, bbox_inches='tight')
plt.show()

"""## 13. Classification Report"""

# Classification Report
print("\n" + "="*70)
print("DETAILED CLASSIFICATION REPORT")
print("="*70 + "\n")

# Get unique labels present in the true_classes
unique_labels = np.unique(true_classes)

# Create a filtered list of target names corresponding to the unique labels
# The train_generator.class_indices dictionary maps class names (strings) to integer indices.
# We need to reverse this to get class names from integer indices, or use class_names_from_gen directly with indices.
# class_names_from_gen is already ordered by the indices from 0 to 11 (as seen in generator output)
filtered_target_names = [class_names_from_gen[i] for i in unique_labels]

report = classification_report(true_classes, predicted_classes,
                              labels=unique_labels, # Specify the actual labels present
                              target_names=filtered_target_names, digits=4)
print(report)

# Save report to file
with open('classification_report.txt', 'w') as f:
    f.write("="*70 + "\n")
    f.write("CATTLE AND BUFFALO CLASSIFICATION MODEL\n")
    f.write("CLASSIFICATION REPORT\n")
    f.write("="*70 + "\n\n")
    f.write(report)
    f.write("\n" + "="*70 + "\n")
    f.write("TEST METRICS SUMMARY\n")
    f.write("="*70 + "\n")
    f.write(f"Loss:      {test_loss:.4f}\n")
    f.write(f"Accuracy:  {test_accuracy:.4f} ({test_accuracy*100:.2f}%)\n")
    f.write(f"AUC:       {test_auc:.4f}\n")
    f.write(f"Precision: {test_precision:.4f}\n")
    f.write(f"Recall:    {test_recall:.4f}\n")
    f.write("="*70 + "\n")

print("\n✅ Classification report saved to 'classification_report.txt'")

"""## 14. ROC Curve and AUC"""

# ROC Curve
plt.figure(figsize=(12, 8))

if num_classes == 2:
    # Binary classification
    fpr, tpr, _ = roc_curve(true_classes, predictions[:, 1])
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, color='darkorange', lw=3,
             label=f'ROC curve (AUC = {roc_auc:.4f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')
else:
    # Multi-class ROC
    y_test_bin = label_binarize(true_classes, classes=range(num_classes))

    colors = ['blue', 'red', 'green', 'orange', 'purple']
    for i in range(num_classes):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], predictions[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, color=colors[i % len(colors)], lw=3,
                label=f'{class_names_from_gen[i]} (AUC = {roc_auc:.4f})')

    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=13, fontweight='bold')
plt.ylabel('True Positive Rate', fontsize=13, fontweight='bold')
plt.title('Receiver Operating Characteristic (ROC) Curve', fontsize=15, fontweight='bold')
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('roc_curve.png', dpi=300, bbox_inches='tight')
plt.show()

"""## 15. Visualize Predictions"""

# Display sample predictions
def display_predictions(generator, model, num_images=20):
    generator.reset()
    x_batch, y_batch = next(generator)

    predictions = model.predict(x_batch[:num_images], verbose=0)
    predicted_classes = np.argmax(predictions, axis=1)
    true_classes = np.argmax(y_batch[:num_images], axis=1)

    rows = 4
    cols = 5
    fig, axes = plt.subplots(rows, cols, figsize=(20, 16))
    axes = axes.ravel()

    for i in range(min(num_images, len(x_batch))):
        axes[i].imshow(x_batch[i])
        axes[i].axis('off')

        pred_class = class_names_from_gen[predicted_classes[i]]
        true_class = class_names_from_gen[true_classes[i]]
        confidence = predictions[i][predicted_classes[i]] * 100

        is_correct = predicted_classes[i] == true_classes[i]
        color = 'green' if is_correct else 'red'
        symbol = '✓' if is_correct else '✗'

        axes[i].set_title(
            f'{symbol} True: {true_class}\nPred: {pred_class}\nConf: {confidence:.1f}%',
            color=color, fontsize=11, fontweight='bold'
        )

    plt.suptitle('Sample Predictions (Green = Correct ✓, Red = Incorrect ✗)',
                fontsize=16, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.savefig('sample_predictions.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Calculate accuracy for this batch
    batch_accuracy = np.sum(predicted_classes == true_classes) / len(predicted_classes)
    print(f"\nBatch accuracy: {batch_accuracy*100:.2f}% ({np.sum(predicted_classes == true_classes)}/{len(predicted_classes)} correct)")

display_predictions(validation_generator, model, num_images=20)

"""## 16. Save the Model"""

print("\n" + "="*70)
print("SAVING MODEL")
print("="*70 + "\n")

# Save the final model in multiple formats
model.save('cattle_buffalo_classifier_final.h5')
print("✅ Model saved as 'cattle_buffalo_classifier_final.h5'")

# Save in SavedModel format (recommended for TensorFlow 2.x)
model.save('cattle_buffalo_classifier_savedmodel')
print("✅ Model saved as 'cattle_buffalo_classifier_savedmodel/'")

# Save model architecture and weights separately
model_json = model.to_json()
with open('model_architecture.json', 'w') as json_file:
    json_file.write(model_json)
model.save_weights('model_weights.h5')
print("✅ Model architecture saved as 'model_architecture.json'")
print("✅ Model weights saved as 'model_weights.h5'")

# Save class names
import json
with open('class_names.json', 'w') as f:
    json.dump({'class_names': class_names_from_gen, 'class_indices': train_generator.class_indices}, f, indent=2)
print("✅ Class names saved as 'class_names.json'")

print("\n" + "="*70)
print("ALL FILES SAVED SUCCESSFULLY!")
print("="*70)

"""## 17. Model Summary Statistics"""

# Calculate F1 Score
from sklearn.metrics import f1_score
f1 = f1_score(true_classes, predicted_classes, average='weighted')

# Create comprehensive summary
summary_text = f"""
{'='*70}
CATTLE AND BUFFALO CLASSIFICATION MODEL
TRAINING SUMMARY
{'='*70}

DATASET INFORMATION:
  Training samples:     {train_generator.samples}
  Validation samples:   {validation_generator.samples}
  Total samples:        {train_generator.samples + validation_generator.samples}
  Number of classes:    {num_classes}
  Classes:              {', '.join(class_names_from_gen)}

MODEL CONFIGURATION:
  Architecture:         Transfer Learning
  Base Model:           MobileNetV2 (ImageNet weights)
  Image Size:           {IMG_HEIGHT}x{IMG_WIDTH} pixels
  Batch Size:           {BATCH_SIZE}
  Initial Learning Rate: {LEARNING_RATE}
  Fine-tune Learning Rate: {LEARNING_RATE/10}

TRAINING CONFIGURATION:
  Phase 1 Epochs:       {len(history.history['accuracy'])}
  Phase 2 Epochs:       {len(history_fine.history['accuracy']) if 'history_fine' in locals() else 'N/A'}
  Total Epochs:         {len(history.history['accuracy']) + (len(history_fine.history['accuracy']) if 'history_fine' in locals() else 0)}
  Data Augmentation:    Rotation, Shift, Zoom, Flip, Brightness

FINAL PERFORMANCE METRICS:
  Test Loss:            {test_loss:.4f}
  Test Accuracy:        {test_accuracy:.4f} ({test_accuracy*100:.2f}%)
  Test AUC:             {test_auc:.4f}
  Test Precision:       {test_precision:.4f}
  Test Recall:          {test_recall:.4f}
  F1 Score (Weighted):  {f1:.4f}

MODEL PARAMETERS:
  Total Parameters:     {model.count_params():,}
  Trainable Parameters: {sum([tf.size(w).numpy() for w in model.trainable_weights]):,}
  Non-trainable Params: {sum([tf.size(w).numpy() for w in model.non_trainable_weights]):,}

CONFUSION MATRIX:
{cm}

{'='*70}
"""

print(summary_text)

# Save summary to file
with open('model_summary.txt', 'w') as f:
    f.write(summary_text)

print("✅ Model summary saved to 'model_summary.txt'")

"""## 18. Test on Individual Images (Inference Function)"""

def predict_single_image(image_path, model, class_names):
    """
    Predict the class of a single image.

    Args:
        image_path: Path to the image file
        model: Trained Keras model
        class_names: List of class names

    Returns:
        Predicted class and confidence
    """
    # Load and preprocess image
    img = load_img(image_path, target_size=(IMG_HEIGHT, IMG_WIDTH))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0

    # Make prediction
    predictions = model.predict(img_array, verbose=0)
    predicted_class_idx = np.argmax(predictions[0])
    confidence = predictions[0][predicted_class_idx] * 100

    # Display results
    plt.figure(figsize=(10, 8))
    plt.imshow(img)
    plt.axis('off')
    plt.title(f'Predicted: {class_names[predicted_class_idx]}\nConfidence: {confidence:.2f}%',
             fontsize=16, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.show()

    # Print detailed predictions
    print(f"\nDetailed predictions for all classes:")
    print("="*50)
    for i, class_name in enumerate(class_names):
        prob = predictions[0][i]*100
        bar = '█' * int(prob / 2)
        print(f"  {class_name:15s}: {prob:6.2f}% {bar}")
    print("="*50)

    return class_names[predicted_class_idx], confidence

# Example: Test on random images from test set
print("\n" + "="*70)
print("TESTING INFERENCE ON SAMPLE IMAGES")
print("="*70 + "\n")

# Get random images from each class
for class_name in class_names_from_gen:
    class_dir = os.path.join(test_dir, class_name)
    images = [f for f in os.listdir(class_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

    if images:
        random_image = np.random.choice(images)
        image_path = os.path.join(class_dir, random_image)

        print(f"\nTesting on {class_name} image: {random_image}")
        predicted_class, confidence = predict_single_image(image_path, model, class_names_from_gen)

        if predicted_class == class_name:
            print(f"✅ CORRECT! Predicted: {predicted_class} (True: {class_name})")
        else:
            print(f"❌ INCORRECT! Predicted: {predicted_class} (True: {class_name})")

"""## 19. Model Performance Analysis"""

# Analyze per-class performance
print("\n" + "="*70)
print("PER-CLASS PERFORMANCE ANALYSIS")
print("="*70 + "\n")

for i, class_name in enumerate(class_names_from_gen):
    class_mask = true_classes == i
    class_predictions = predicted_classes[class_mask]
    class_true = true_classes[class_mask]

    class_accuracy = np.sum(class_predictions == class_true) / len(class_true)

    print(f"{class_name}:")
    print(f"  Total samples: {len(class_true)}")
    print(f"  Correctly classified: {np.sum(class_predictions == class_true)}")
    print(f"  Accuracy: {class_accuracy*100:.2f}%")
    print()

# Plot per-class accuracy
class_accuracies = []
for i in range(num_classes):
    class_mask = true_classes == i
    class_predictions = predicted_classes[class_mask]
    class_true = true_classes[class_mask]
    class_accuracy = np.sum(class_predictions == class_true) / len(class_true)
    class_accuracies.append(class_accuracy)

plt.figure(figsize=(10, 6))
bars = plt.bar(class_names_from_gen, class_accuracies, color=['skyblue', 'lightcoral'],
               edgecolor='navy', linewidth=2)
plt.axhline(y=test_accuracy, color='red', linestyle='--', linewidth=2, label=f'Overall Accuracy: {test_accuracy:.2%}')
plt.xlabel('Class', fontsize=13, fontweight='bold')
plt.ylabel('Accuracy', fontsize=13, fontweight='bold')
plt.title('Per-Class Accuracy', fontsize=15, fontweight='bold')
plt.ylim([0, 1.1])
plt.legend(fontsize=11)
plt.grid(axis='y', alpha=0.3)

# Add value labels on bars
for bar, acc in zip(bars, class_accuracies):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
            f'{acc:.2%}', ha='center', va='bottom', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('per_class_accuracy.png', dpi=300, bbox_inches='tight')
plt.show()